Repository qdrant/qdrant, pull requests merged in 2024-06, with the labels that each got.

#4375 Fix inplace updates for sparse index
  lib/segment/src/index/hnsw_index/hnsw.rs
  lib/segment/src/index/plain_payload_index.rs
  lib/segment/src/index/sparse_index/sparse_vector_index.rs
  lib/segment/src/index/vector_index_base.rs
  lib/segment/src/segment.rs
  lib/segment/src/vector_storage/simple_sparse_vector_storage.rs
  lib/segment/src/vector_storage/vector_storage_base.rs
  lib/sparse/src/index/inverted_index/inverted_index_compressed_immutable_ram.rs
  lib/sparse/src/index/inverted_index/inverted_index_compressed_mmap.rs
  lib/sparse/src/index/inverted_index/inverted_index_immutable_ram.rs
  lib/sparse/src/index/inverted_index/inverted_index_mmap.rs
  lib/sparse/src/index/inverted_index/inverted_index_ram.rs
  lib/sparse/src/index/inverted_index/mod.rs
  lib/sparse/src/index/posting_list.rs
  lib/sparse/src/index/search_context.rs
  tests/openapi/openapi_integration/test_sparse_update.py
Labels: bug

#4517 Fix web UI index path http security headers
  src/actix/mod.rs
  tools/sync-web-ui.sh
Labels: bug, chore

#4578 Fail early when encountering out-of-storage during optimization
  Cargo.lock
  lib/collection/src/collection_manager/optimizers/segment_optimizer.rs
  lib/common/common/src/disk.rs
  lib/common/common/src/lib.rs
  lib/segment/Cargo.toml
  lib/segment/src/common/mod.rs
Labels: 🙋 Bounty claim

#4562 Extract web ui factory into module with tests
  src/actix/mod.rs
  src/actix/web_ui.rs
Labels: chore
