Repository qdrant/qdrant, pull requests merged in 2025-08, with the labels that each got.

#6977 Buffered mutable bool index
  lib/segment/src/common/buffered_dynamic_flags.rs
  lib/segment/src/index/field_index/bool_index/mod.rs
  lib/segment/src/index/field_index/bool_index/mutable_bool_index.rs
  lib/segment/src/index/field_index/field_index_base.rs
  lib/segment/src/index/field_index/index_selector.rs
Labels: next patch

#7006 Update if
  docs/grpc/docs.md
  docs/redoc/master/openapi.json
  lib/api/build.rs
  lib/api/src/grpc/proto/points.proto
  lib/api/src/grpc/qdrant.rs
  lib/api/src/rest/schema.rs
  lib/collection/src/collection_manager/segments_updater.rs
  lib/collection/src/operations/mod.rs
  lib/collection/src/operations/operation_effect.rs
  lib/collection/src/operations/point_ops.rs
  lib/collection/src/operations/vector_ops.rs
  lib/collection/src/operations/verification/update.rs
  lib/collection/src/shards/conversions.rs
  lib/collection/src/shards/remote_shard.rs
  lib/collection/src/shards/shard_holder/resharding.rs
  lib/collection/src/tests/sparse_vectors_validation_tests.rs
  lib/segment/src/types.rs
  lib/storage/src/rbac/ops_checks.rs
  src/common/update.rs
  src/tonic/api/update_common.rs
  tests/openapi/test_conditional_update.py
Labels: do not merge

#6946 Clean up `GraphLayers::search_entry_on_level` a bit
  lib/segment/src/index/hnsw_index/gpu/gpu_insert_context.rs
  lib/segment/src/index/hnsw_index/graph_layers.rs
Labels: chore
